# Generated by Django 4.2.11 on 2024-03-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Наименование', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='стоимость', max_digits=8)),
            ],
        ),
    ]
